// <auto-generated />
using CslAppEntityFrameworkCore.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CslAppEntityFrameworkCore.Migrations
{
    [DbContext(typeof(Db))]
    partial class DbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CslAppEntityFrameworkCore.Models.Address", b =>
                {
                    b.Property<int>("PeopleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("peopleId");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("number");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("street");

                    b.HasKey("PeopleId");

                    b.ToTable("address");
                });

            modelBuilder.Entity("CslAppEntityFrameworkCore.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("peoples");
                });

            modelBuilder.Entity("CslAppEntityFrameworkCore.Models.Address", b =>
                {
                    b.HasOne("CslAppEntityFrameworkCore.Models.People", "People")
                        .WithOne("Address")
                        .HasForeignKey("CslAppEntityFrameworkCore.Models.Address", "PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("People");
                });

            modelBuilder.Entity("CslAppEntityFrameworkCore.Models.People", b =>
                {
                    b.Navigation("Address");
                });
#pragma warning restore 612, 618
        }
    }
}
